tab_bar_edge top
tab_bar_style separator
tab_bar_show_new_tab_button yes
tab_bar_min_tabs 1

map ctrl+shift+, previous_tab
map ctrl+shift+. next_tab
map ctrl+shift+h move_tab_backward
map ctrl+shift+l move_tab_forward

